DROP TABLE GD_ACCOUNT;
CREATE TABLE GD_ACCOUNT(ACC_NO INT PRIMARY KEY, ACC_NAME VARCHAR(20), ACC_TYPE VARCHAR(20), BAL INT);
DESC GD_ACCOUNT;


INSERT INTO GD_ACCOUNT VALUES (101,'GD','SAVINGS',1200);
INSERT INTO GD_ACCOUNT VALUES (102,'GD','SAVINGS',1200);
INSERT INTO GD_ACCOUNT VALUES (103,'GD','SAVINGS',1200);
COMMIT;

DELETE FROM GD_ACCOUNT WHERE ACC_NO=1;
UPDATE GD_ACCOUNT SET ACC_NO=2,ACC_NAME='XYZ',ACC_TYPE='SAVING',BAL=12000 WHERE  ACC_NO=1;
DELETE FROM GD_ACCOUNT ;
--IF YOU DONT COMMIT YOUR ECLIPSE CODE WILL KEEP ON WAITING TO PERFORM OPERATION HENCE JDBC WONT WORK HENCE ALL THE TIME DO COMMIT WITHOUT FAIL FOR ALL DML
COMMIT;
SELECT * FROM GD_ACCOUNT;


--ALTER TABLE GD_ACCOUNT DISABLE PRIMARY KEY;

